[package]
name = "ruby-format"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
colored = "3.1.1"
glob = "0.3.4"
monotonic-clock = "0.0.7"
ruby-prism = "1.9.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml = "0.9.34"
tempdir = "0.3.7"
walkdir = "2"
yaml-rust = "0.4.5"
